server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkin_service?createDatabaseIfNotExist=true
    username: root
    password: Suraj@1629
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
